version: "3"


services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"
    restart: always