# Generated by Django 3.2 on 2021-05-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersStartedConv",
            fields=[
                (
                    "user_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Телеграм id"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, null=True, verbose_name="Имя в ТГ"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Фамилия в ТГ",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Никнеим в ТГ",
                    ),
                ),
                ("is_bot", models.BooleanField(verbose_name="Бот")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Зарегистрирован в Боте"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователя",
                "verbose_name_plural": "пользователи",
                "db_table": "Telegram_All_Users",
            },
        ),
        migrations.CreateModel(
            name="PartyUsersForNearestParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Имя для вечеринки"
                    ),
                ),
                (
                    "real_last_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Фамилия для вечеринки"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Номер для вечеринки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Зарегестрировался"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram_bot.usersstartedconv",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователя текущей вечеринки",
                "verbose_name_plural": "Пользователи текущей вечеринки",
                "db_table": "Telegram_Party_Users_For_Nearest_Party",
            },
        ),
        migrations.CreateModel(
            name="AllPartyUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(max_length=30, verbose_name="Имя для вечеринки"),
                ),
                (
                    "real_last_name",
                    models.CharField(
                        max_length=30, verbose_name="Фамилия для вечеринки"
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=30, verbose_name="Номер для вечеринки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram_bot.usersstartedconv",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователя всех вечеринок",
                "verbose_name_plural": "Пользователи всех вечеринок",
                "db_table": "Telegram_All_Party_Users",
            },
        ),
    ]
