# Generated by Django 3.2 on 2021-04-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersstartedconv',
            name='id',
        ),
        migrations.AlterField(
            model_name='usersstartedconv',
            name='user_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм id'),
        ),
    ]
