# Generated by Django 3.2 on 2021-04-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_auto_20210420_0356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractionlog',
            options={'ordering': ['action']},
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.usersstartedconv'),
        ),
    ]
