# Generated by Django 3.2 on 2021-04-20 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_auto_20210420_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractionlog',
            options={},
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.usersstartedconv'),
        ),
        migrations.AlterField(
            model_name='usersstartedconv',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм id'),
        ),
    ]
