# Generated by Django 3.2 on 2021-05-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "О нас",
                "verbose_name_plural": "О нас",
                "db_table": "Main_About",
            },
        ),
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Барное меню",
                "verbose_name_plural": "Барное меню",
                "db_table": "Main_Bar",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "DJ SCHOOL",
                "verbose_name_plural": "DJ SCHOOL",
                "db_table": "Main_School",
            },
        ),
    ]
