# Generated by Django 3.2 on 2021-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='text',
            field=models.CharField(max_length=10000, verbose_name='Описание'),
        ),
    ]
