# Generated by Django 3.2 on 2021-04-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bar',
            table='Bar',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
        migrations.AlterModelTable(
            name='party',
            table='Party',
        ),
        migrations.AlterModelTable(
            name='school',
            table='School',
        ),
    ]
