# Generated by Django 3.2 on 2021-04-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210412_1630'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bar',
            table='Main_Bar',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='Main_Menu',
        ),
        migrations.AlterModelTable(
            name='party',
            table='Main_Party',
        ),
        migrations.AlterModelTable(
            name='school',
            table='Main_School',
        ),
    ]
