# Generated by Django 3.2 on 2021-04-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210412_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('telegram_id', models.IntegerField(max_length=15)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
